
import './globals.css'
import Header from '@/app/components/header'


export const metadata = {
  title: 'Canteen Revamp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div><Header/></div>
        {children}
        </body>
    </html>
  )
}
